SELECT
    COLUMN_NAME,
    AVG(CARDINALITY) AS AVG_CARDINALITY
FROM INFORMATION_SCHEMA.STATISTICS
WHERE
    TABLE_SCHEMA = 'SCHEMA_NAME'
    AND TABLE_NAME = 'TABLE_NAME'
    AND INDEX_NAME <> 'PRIMARY'
GROUP BY COLUMN_NAME
ORDER BY AVG_CARDINALITY DESC;
