-- Show table creation statement:
SHOW CREATE TABLE TABLE_SCHEMA;

-- Show table indexes:
SHOW KEYS
FROM SCHEMA_NAME.TABLE_NAME
WHERE KEY_NAME = 'PRIMARY';

-- Show table constraints:
SELECT
    COLUMN_NAME,
    CONSTRAINT_NAME,
    REFERENCED_TABLE_NAME,
    REFERENCED_COLUMN_NAME
FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE
WHERE
    REFERENCED_TABLE_NAME IS NOT NULL
    AND TABLE_SCHEMA = 'SCHEMA_NAME'
    AND TABLE_NAME = 'TABLE_NAME'
ORDER BY COLUMN_NAME;
